server:
  port: 6001

spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.63:8848 #注册到Nacos
        group: dev
  security:
    basic:
      enabled: false
    user:
      name: admin
      password: 123456
  redis: #redis 通用配置
    host: 192.168.1.63
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100
    timeout: 5000
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@192.168.1.63:1521:helowin
#    username: nw_prod
#    password: nw_prod
  datasource:
    url: jdbc:mysql://192.168.1.63:3306/alipay?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  rabbitmq:
  #    host: 192.168.1.63
  #    port: 5672
  #    username: guest
  #    password: guest
  #    publisher-confirm-type: correlated
  #    publisher-returns: true #消息发送到交换机确认机制，是否返回回调
  #    listener: #采用手动应答
  #      simple:
  #        acknowledge-mode: manual
  #        concurrency: 1 #指定最小的消费者数量
  #        max-concurrency: 1 #指定最大的消费者数量
  #        retry:
  #          enabled: true #是否重试